spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/hw_7?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
  sql:
    init:
      platform: mysql
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      mode: always

  #  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 50MB
server:
  port: 8078
